export const fn = async (req, res, next) => {
  try {
  } catch (err) {
    console.log(err);
  }
};
